# Generated by Django 5.2 on 2025-07-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_conos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocono',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidocono',
            name='tamanio_cono',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidocono',
            name='variante',
            field=models.CharField(choices=[('carnivoro', 'Carnívoro'), ('vegetariano', 'Vegetariano'), ('saludable', 'Saludable')], max_length=20),
        ),
    ]
